name: ICore
main: AkeKy\ICore
version: 1.0.0
api:
- 1.12.0
- 2.0.0
load: STARTUP
author: PocketMine Team
authors: [rewrite by AkeKy]
description: Prevents people to impersonate an account, requering registration and login when connecting.
commands:
 login:
  permission: login
  description: "§bLogs into an account"
 register:
  permission: register
  description: "§bRegisters an account"
 rank:
  permission: rank
  description: '§bRanks'
 vip:
  permission: vip
  description: '§bHow to donate'
 ru:
  permission: ru
  description: '§bRule'
 spawn:
  permission: spawn
  description: '§bTP to Spawn'
 fe:
  permission: fe
  description: '§bEnable Fly'
 fd:
  permission: fd
  description: '§bDisable Fly'
 ve:
  permission: ve
  description: '§bEnable Hidden'
 vd:
  permission: vd
  description: '§bDisable Hidden'
 stats:
  permission: stats
  description: '§bCheck scores'
 vips:
  permission: vips
  description: '§bAdd Vips'
 restart:
  permission: restart
  description: '§bTime to Restart'
permissions:
 login:
  default: true
 register:
  default: true
 rank:
  default: true
 vip:
  default: true
 ru:
  default: true
 spawn:
  default: true
 fe:
  default: op
 fd:
  default: op
 ve:
  default: op
 vd:
  default: op
 stats:
  default: true
 vips:
  default: op
 restart:
  default: true
