#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#Cancle id block
block-NoUpdate: ["8","9","10","11","12"]
#Cancle PvP in world
world-NoPvP: ["Hub2","HZ1"]
#Cancle Break,Place Block
block-CancleBP: ["Hub2","PVP1"]
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
PvPStatsdataProvider: yaml
mysql-settings:
    host: "127.0.0.1"
    port: 3306
    user: "user"
    password: "password"
    database: "databaseName"
#
#Color Symbol
color-symbol: "§"
#
#/stats Command format
other-command-format: "§r§l§b@player§r§6('s) Stats:\n§r§o§e- §r§aKills: §r§l§6@kills\n§r§o§e- §r§aDeaths: §r§l§6@deaths\n§r§o§e- §r§aK-D Ratio: §r§l§6@kdratio"
self-command-format: "§r§6Your Stats:\n§r§o§e- §r§aKills: §r§l§6@kills\n§r§o§e- §r§aDeaths: §r§l§6@deaths\n§r§o§e- §r§aK-D Ratio: §r§l§6@kdratio"

#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
# Default config for SimpleAuth plugin

#Sets the data provider (yaml, sqlite3, mysql, none).
#Only use none when there is another plugin that will integrate its dataProvider with SimpleAuth
#Be aware that data is not automatically moved between data providers.
SimpleAuthdataProvider: yaml

#For MySQL:
#SimplAuthdataProviderSettings:
# host: "127.0.0.1"
# port: 3306
# user: "user"
# password: "password"
# database: "databaseName"
SimplAuthdataProviderSettings: []

#If enabled, existing logged-in accounts won't be kicked if a new player joins with the same name
forceSingleSession: true

#Sets the minimum amount of characters to be used when registering a new account
minPasswordLength: 6

#Will block user after this number of failed attempts. Set to 0 to disable
blockAfterFail: 6

#If enabled, accounts that are using the same unique id (ip + clientId + name) when logging in again will be automatically authenticated
authenticateByLastUniqueId: false

#If enabled, will set all the permissions for simleauth.command.register to false
disableRegister: false

#If enabled, will set all the permissions for simleauth.command.login to false
disableLogin: false

#Number of seconds to wait for a player to be authenticated. If false, disables the timeout
#TODO
authenticateTimeout: 120
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
TimeToRestart: "30"
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
###############
#ChatDefender #
###############
similarity: 1
  # Required similarity of messages to be considered spam
  # Uses similar_text()
ratelimit: 1
  # Mininum time between messages for them to be considered spam
  # if it is 1 then messages sent 1 second apart or less will be spam
baseblocklength: 30
  # Block length in seconds
  # Will increase with repeated blocks
###############
# Broadcaster #
###############
time: 10
messages:
 - "§8§l.\n§a1\n§8§l."